/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import java.util.Random;
import javax.swing.JOptionPane;
import referenciaBanco.Cliente;
import referenciaBanco.Vendedor;

/**
 *
 * @author willg
 */
public class Cadastro extends javax.swing.JFrame {

    private String bd;
    private int idVend;
    private int idCli;

    protected persistencia.Cliente clientes;
    protected persistencia.Vendedor vendedores;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    public Cadastro(String bd) {
        initComponents();
        this.bd = bd;
        vendedores = new persistencia.Vendedor(bd);
        vendedores.obtem();

        idVend = vendedores.getVendedor().get(vendedores.getVendedor().size() - 1).getIdvendedor() + 1;

        tfId.setText(idVend + "");

        clientes = new persistencia.Cliente(bd);
        clientes.obtem();

        idCli = clientes.getCliente().get(clientes.getCliente().size() - 1).getIdcliente() + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Cliente = new javax.swing.JRadioButton();
        Vendedor = new javax.swing.JRadioButton();
        tfNome = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        tfRepeteSenha = new javax.swing.JPasswordField();
        tfId = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        tfRg = new javax.swing.JTextField();
        tfFone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();

        grupoRadio.add(Cliente); grupoRadio.add(Vendedor);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar");

        Cliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cliente.setText("Cliente");
        Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        Vendedor.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Vendedor.setSelected(true);
        Vendedor.setText("Vendedor");
        Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorActionPerformed(evt);
            }
        });

        tfNome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfNome.setText("Nome");
        tfNome.setToolTipText("");
        tfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNomeFocusGained(evt);
            }
        });
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfUsuario.setText("Usuario");
        tfUsuario.setToolTipText("");
        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusGained(evt);
            }
        });
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });

        tfSenha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfSenha.setText("senha");
        tfSenha.setPreferredSize(new java.awt.Dimension(60, 26));
        tfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSenhaFocusGained(evt);
            }
        });

        tfRepeteSenha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfRepeteSenha.setText("senha");
        tfRepeteSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRepeteSenhaFocusGained(evt);
            }
        });

        tfId.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfId.setEnabled(false);
        tfId.setFocusable(false);

        tfCpf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfCpf.setText("CPF");
        tfCpf.setEnabled(false);
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCpfFocusGained(evt);
            }
        });

        tfRg.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfRg.setText("RG");
        tfRg.setEnabled(false);
        tfRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRgFocusGained(evt);
            }
        });

        tfFone.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfFone.setText("Fone");
        tfFone.setEnabled(false);
        tfFone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFoneFocusGained(evt);
            }
        });

        tfEmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfEmail.setText("E-mail");
        tfEmail.setEnabled(false);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
        });

        tfEndereco.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfEndereco.setText("Endereço");
        tfEndereco.setEnabled(false);
        tfEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEnderecoFocusGained(evt);
            }
        });

        tfNumero.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfNumero.setText("Número");
        tfNumero.setEnabled(false);
        tfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNumeroFocusGained(evt);
            }
        });

        tfBairro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfBairro.setText("Bairro");
        tfBairro.setEnabled(false);
        tfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBairroFocusGained(evt);
            }
        });

        tfCidade.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfCidade.setText("Cidade");
        tfCidade.setEnabled(false);
        tfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCidadeFocusGained(evt);
            }
        });

        tfEstado.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tfEstado.setText("Estado");
        tfEstado.setEnabled(false);
        tfEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEstadoFocusGained(evt);
            }
        });

        btEnviar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfBairro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCpf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEstado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(Cliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Vendedor)
                        .addContainerGap(163, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfCidade)
                            .addComponent(tfNumero)
                            .addComponent(tfRg)
                            .addComponent(tfRepeteSenha)
                            .addComponent(tfUsuario)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cliente)
                    .addComponent(Vendedor)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRepeteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnviar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusGained
        tfNome.setText("");
    }//GEN-LAST:event_tfNomeFocusGained

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusGained
        tfUsuario.setText("");
    }//GEN-LAST:event_tfUsuarioFocusGained

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuarioActionPerformed

    private void tfSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSenhaFocusGained
        tfSenha.setText("");
    }//GEN-LAST:event_tfSenhaFocusGained

    private void tfRepeteSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRepeteSenhaFocusGained
        tfRepeteSenha.setText("");
    }//GEN-LAST:event_tfRepeteSenhaFocusGained

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        tfCpf.setEnabled(true);
        tfRg.setEnabled(true);
        tfFone.setEnabled(true);
        tfEmail.setEnabled(true);
        tfEndereco.setEnabled(true);
        tfNumero.setEnabled(true);
        tfBairro.setEnabled(true);
        tfCidade.setEnabled(true);
        tfEstado.setEnabled(true);

        tfId.setText(idCli + "");
    }//GEN-LAST:event_ClienteActionPerformed

    private void VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorActionPerformed
        tfCpf.setEnabled(false);
        tfRg.setEnabled(false);
        tfFone.setEnabled(false);
        tfEmail.setEnabled(false);
        tfEndereco.setEnabled(false);
        tfNumero.setEnabled(false);
        tfBairro.setEnabled(false);
        tfCidade.setEnabled(false);
        tfEstado.setEnabled(false);

        tfId.setText(idVend + "");
    }//GEN-LAST:event_VendedorActionPerformed

    private void tfCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusGained
        tfCpf.setText("");
    }//GEN-LAST:event_tfCpfFocusGained

    private void tfRgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRgFocusGained
        tfRg.setText("");
    }//GEN-LAST:event_tfRgFocusGained

    private void tfFoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFoneFocusGained
        tfFone.setText("");
    }//GEN-LAST:event_tfFoneFocusGained

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        tfEmail.setText("");
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEnderecoFocusGained
        tfEndereco.setText("");
    }//GEN-LAST:event_tfEnderecoFocusGained

    private void tfNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusGained
        tfNumero.setText("");
    }//GEN-LAST:event_tfNumeroFocusGained

    private void tfBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBairroFocusGained
        tfBairro.setText("");
    }//GEN-LAST:event_tfBairroFocusGained

    private void tfCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCidadeFocusGained
        tfCidade.setText("");
    }//GEN-LAST:event_tfCidadeFocusGained

    private void tfEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEstadoFocusGained
        tfEstado.setText("");
    }//GEN-LAST:event_tfEstadoFocusGained

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        if (Cliente.isSelected()) {
            if (tfNome.getText().length() > 3 && tfUsuario.getText().length() > 3
                    && tfSenha.getPassword().length > 0 && tfRepeteSenha.getPassword().length > 0
                    && tfCpf.getText().length() >= 11 && tfRg.getText().length() >= 10
                    && tfFone.getText().length() >= 9 && tfEmail.getText().length() >= 8
                    && tfEndereco.getText().length() > 3 && tfNumero.getText().length() > 0
                    && tfBairro.getText().length() > 3 && tfCidade.getText().length() > 3
                    && tfEstado.getText().length() >= 2) {

                boolean existe = false, senha = false;
                for (referenciaBanco.Cliente v : clientes.getCliente()) {
                    if (v.getUsuario().equals(tfUsuario.getText())) {
                        existe = true;
                        JOptionPane.showMessageDialog(null,
                                "Usuário já existente", "Erro de validação",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }

                String senhaS = String.copyValueOf(tfSenha.getPassword());
                String repSenha = String.copyValueOf(tfRepeteSenha.getPassword());

                if (!senhaS.equals(repSenha)) {
                    senha = true;
                    JOptionPane.showMessageDialog(null,
                            "Senhas não são iguais", "Erro de validação",
                            JOptionPane.ERROR_MESSAGE);
                }
                if (!existe && !senha) {
                    referenciaBanco.Cliente cliente = new Cliente();
                    cliente.setNome(tfNome.getText());
                    cliente.setSenha(String.copyValueOf(tfSenha.getPassword()), true);
                    cliente.setUsuario(tfUsuario.getText());
                    cliente.setCpf(tfCpf.getText());
                    cliente.setRg(tfRg.getText());
                    cliente.setFone(tfFone.getText());
                    cliente.setEmail(tfEmail.getText());
                    cliente.setEndereco(tfEndereco.getText());
                    cliente.setNumero(Integer.parseInt(tfNumero.getText()));
                    cliente.setBairro(tfBairro.getText());
                    cliente.setCidade(tfCidade.getText());
                    cliente.setEstado(tfEstado.getText());
                    cliente.setIdcliente(idCli);

                    Random r = new Random();
                    int rand = r.nextInt(1000);

                    referenciaBanco.Email e = new referenciaBanco.Email(
                            "Cadastro Pessoal", "Olá "+ cliente.getNome()+" use o código a seguir para "
                            + "verificar o e-mail: " + rand + ".\nSe você não solicitou este cadastro, ignorar.", cliente.getEmail());
                    e.enviaEmail();

                    String verificar = JOptionPane.showInputDialog("Código enviado por e-mail");

                    if (Integer.parseInt(verificar) == rand) {
                        clientes.setCliente(cliente);
                        clientes.grava();

                        JOptionPane.showMessageDialog(null,
                                "Cliente salvo com sucesso", "Cadastro",
                                JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }

                }

            }
        } else {
            if (tfNome.getText().length() > 3 && tfUsuario.getText().length() > 3
                    && tfSenha.getPassword().length > 0 && tfRepeteSenha.getPassword().length > 0) {
                boolean existe = false, senha = false;
                for (referenciaBanco.Vendedor v : vendedores.getVendedor()) {
                    if (v.getUsuario().equals(tfUsuario.getText())) {
                        existe = true;
                        JOptionPane.showMessageDialog(null,
                                "Usuário já existente", "Erro de validação",
                                JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }

                String senhaS = String.copyValueOf(tfSenha.getPassword());
                String repSenha = String.copyValueOf(tfRepeteSenha.getPassword());

                if (!senhaS.equals(repSenha)) {
                    senha = true;
                    JOptionPane.showMessageDialog(null,
                            "Senhas não são iguais", "Erro de validação",
                            JOptionPane.ERROR_MESSAGE);
                }
                if (!existe && !senha) {
                    referenciaBanco.Vendedor vendedor = new Vendedor();
                    vendedor.setNome(tfNome.getText());
                    vendedor.setSenha(String.copyValueOf(tfSenha.getPassword()), true);
                    vendedor.setUsuario(tfUsuario.getText());
                    vendedor.setIdvendedor(idVend);

                    vendedores.setVendedor(vendedor);
                    vendedores.grava();

                    JOptionPane.showMessageDialog(null,
                            "Vendedor salvo com sucesso", "Cadastro",
                            JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cliente;
    private javax.swing.JRadioButton Vendedor;
    private javax.swing.JButton btEnviar;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfFone;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JPasswordField tfRepeteSenha;
    private javax.swing.JTextField tfRg;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
